source 3.storedprocedures/1.DoesUserHavePermissionToGroup.sql
source 3.storedprocedures/1.GroupRemoveUser.sql
source 3.storedprocedures/1.GroupUpdateUserPermissions.sql
source 3.storedprocedures/1.clientsettingscreate.sql
source 3.storedprocedures/1.clientsettingsget.sql
source 3.storedprocedures/1.clientsettingsset.sql
source 3.storedprocedures/1.doesuserhavepermissiontosubscription.sql
source 3.storedprocedures/1.doesuserhavepermissiontosystem.sql
source 3.storedprocedures/1.getpermissionforaction.sql
source 3.storedprocedures/1.getusershighestsystempermission.sql
source 3.storedprocedures/1.groupassociatewithuser.sql
source 3.storedprocedures/1.groupcreate.sql
source 3.storedprocedures/1.groupdelete.sql
source 3.storedprocedures/1.groupget.sql
source 3.storedprocedures/1.groupupdate.sql
source 3.storedprocedures/1.indexsettingscreate.sql
source 3.storedprocedures/1.indexsettingsget.sql
source 3.storedprocedures/1.logcreate.sql
source 3.storedprocedures/1.modulecreate.sql
source 3.storedprocedures/1.moduleget.sql
source 3.storedprocedures/1.permissioncreate.sql
source 3.storedprocedures/1.sessioncreate.sql
source 3.storedprocedures/1.sessiondelete.sql
source 3.storedprocedures/1.sessionget.sql
source 3.storedprocedures/1.sessionupdate.sql
source 3.storedprocedures/1.subscriptioncreate.sql
source 3.storedprocedures/1.subscriptiondelete.sql
source 3.storedprocedures/1.subscriptioninfoget.sql
source 3.storedprocedures/1.subscriptionupdate.sql
source 3.storedprocedures/1.ticketcreate.sql
source 3.storedprocedures/1.ticketget.sql
source 3.storedprocedures/1.ticketuse.sql
source 3.storedprocedures/1.usercreate.sql
source 3.storedprocedures/1.userdelete.sql
source 3.storedprocedures/1.userget.sql
source 3.storedprocedures/1.userinfoget.sql
source 3.storedprocedures/1.userinfogetwithgrouppermission.sql
source 3.storedprocedures/1.usersettingsdelete.sql
source 3.storedprocedures/1.usersettingsget.sql
source 3.storedprocedures/1.usersettingsset.sql
